application: ambient-wall
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /dashboard/.*
  script: dashboard.py
  login: required

- url: /.*
  script: main.py
